#!/bin/sh

if (( USER_ID )); then
	echo >&2 "===> Run ${0##*/} as root"
	exit 1
fi

packages=(
	aria2
	bsdfan
	bspwm
	cursor-dmz-theme
	dbus
	dmenu
	doas
	jetbrains-mono
	lemonbar-xft
	libva-intel-driver
	micro
	mkfontscale
	mpv
	nsxiv
	openrsync
	optipng
	paratype
	pkg
	rdate
	setxkbmap
	slock
	sterm
	xclip
	xf86-video-intel
	xmodmap
	xorg-minimal
	xprop
	xrdb
	xset
	xsetroot
	xtitle
)
#	openntpd

dependencies=(
	curl
	desktop-file-utils
	llvm19
)

pkg update

mkdir -p /usr/local/etc/pkg/repos /usr/local/pkgs
cp configs/local.conf /usr/local/etc/pkg/repos/
cp ~/llvm19/llvm19*.pkg /usr/local/pkgs/
pkg repo /usr/local/pkgs

for dependency in "${dependencies[@]}"; do
	sqlite3 /var/db/pkg/local.sqlite "delete from deps where name='$dependency';"
done

for package in "${packages[@]}"; do
	pkg info -e "$package" || pkg install -y "$package"
done

echo "0 */4 * * * root rdate -nav ru.pool.ntp.org" | crontab -

build_pkgs() {
	if [ ! -f /etc/wpa_supplicant.conf ]; then
		cat <<- 'END' | unexpand > /etc/wpa_supplicant.conf
			ctrl_interface=/var/run/wpa_supplicant
			eapol_version=2
			ap_scan=1
			fast_reauth=1

			network={
			        ssid="KPECT"
			        psk=<SET KEYPASS HERE>
			}
		END
	fi

	if [ ! -f ${DSTDIR}/etc/ntpd.conf ]; then
		cat <<- 'END' > ${DSTDIR}/etc/ntpd.conf
			servers by.pool.ntp.org
			sensor *
			constraints from "https://ya.ru"
		END
	fi

	# if ! sysrc -qc sndiod_enable; then
	# 	sysrc sndiod_enable="YES"
	# 	sysrc sndiod_flags="-f rsnd/0 -c 0:7 -j on -m play -s default -m mon -s monitor"
	# fi
	if ! sysrc -qc openntpd_enable; then
		sysrc openntpd_enable="YES"
		sysrc openntpd_flags="-s"
	fi
}
