#!/bin/sh
#
# /usr/local/etc/rc.d/bsdfan: control fan speed using temperature sensor
#

command='bsdfan'
flags='-d'
#pidfile="/var/run/${command}.pid"

case "$1" in
start)		if [ "$RC_BOOT" ] || ! pgrep -q "$command"; then
			if ! limits -C daemon "$command" "$flags"; then
				echo >&2 "$command failed"
				exit 1
			fi
		fi
		;;
stop)		if [ -f "$pidfile" ]; then
			kill $(< "$pidfile")
			rm -f "$pidfile"
		fi
		;;
restart)	"$0" stop
		"$0" start
		;;
*)		echo "${0##*/} [start|stop|restart]"
		exit
		;;
esac
