#!/bin/sh
#
# /usr/local/etc/rc.d/dbus: dbus messagebus daemon
#

command='dbus-daemon'
flags='--system'
midfile='/var/db/dbus/machine-id'
pidfile='/var/run/dbus/pid'

case "$1" in
start)		if [ ! -d /var/db/dbus ]; then
			mkdir /var/db/dbus
		fi
		if [ ! -d /var/run/dbus ]; then
			mkdir /var/run/dbus
		fi
		if [ ! -f "$midfile" ]; then
			dbus-uuidgen --ensure="$midfile"
		fi
		if [ "$RC_BOOT" ] || ! pgrep -q "$command"; then
			if ! limits -C daemon "$command" "$flags"; then
				echo >&2 "$command failed"
				exit 1
			fi
		fi
		;;
stop)		if [ -f "$pidfile" ]; then
			kill $(< "$pidfile")
			rm -f "$pidfile"
		fi
		;;
restart)	"$0" stop
		"$0" start
		;;
*)		echo "${0##*/} [start|stop|restart]"
		exit
		;;
esac
