# configuration file for newsyslog
#
# logfilename          [owner:group]    mode count size when    flags [/pid_file] [sig_num]
#/var/log/all.log			600  7	   *	@T00	X
/var/log/auth.log			600  7	   1000	@0101T	XC
#/var/log/console.log			600  5	   1000	*	X
/var/log/cron				600  3	   1000	*	XC
/var/log/daemon.log			644  5	   1000	@0101T	XC
/var/log/debug.log			600  7	   1000	*	XC
/var/log/devd.log			644  3	   1000	*	XC
#/var/log/init.log			644  3	   1000	*	X
/var/log/maillog			640  7	   1000	*	XC
/var/log/messages			644  5	   1000	@0101T	XC
/var/log/security			600  10	   1000	*	XC
/var/log/utx.log			644  3	   *	@01T05	B

<include> /etc/newsyslog.conf.d/[!.]*.conf
<include> /usr/local/etc/newsyslog.conf.d/[!.]*.conf
