# set fingerprints "/etc/pf.os"
set loginterface egress
set block-policy drop
set skip on lo

table <whitelist> const { 192.168.0.0/16 }
table <bruteforce> persist
table <blacklist> const {
	0.0.0.0/8
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.0.0.0/24
	192.0.2.0/24
	198.18.0.0/15
	198.51.100.0/24
	203.0.113.0/24
	224.0.0.0/4
	233.252.0.0/24
	240.0.0.0/4
}

scrub in all random-id no-df
match out on egress set prio ( 3, 5 )
match proto { tcp udp } to port { ssh domain } set prio 4
block in quick on egress from { no-route urpf-failed <blacklist> }
block in log quick from <bruteforce>
block all
pass out quick inet modulate state
pass in quick inet proto tcp from <whitelist> to (egress) port ssh keep state \
	( max-src-conn 8, max-src-conn-rate 5/3, overload <bruteforce> flush global )
