set loginterface egress
set block-policy drop
set skip on lo

table <bruteforce> persist
table <whitelist> const {
	192.168.0.0/16
	224.0.0.0/4
}
table <blacklist> const {
	0.0.0.0/8
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.0.0.0/24
	192.0.2.0/24
	198.18.0.0/15
	198.51.100.0/24
	203.0.113.0/24
	233.252.0.0/24
	240.0.0.0/4
}

match in all scrub (no-df)
match out all scrub (random-id)
match out on egress set prio (3, 5)
match out proto udp to port domain set prio 4
block in quick on egress from { no-route urpf-failed <blacklist> }
block in log quick from <bruteforce>
block all
pass out quick inet modulate state
pass in quick inet from <whitelist> to (egress)
pass in log quick inet proto tcp to (egress) port ssh keep state (max-src-conn 5, max-src-conn-rate 5/3, overload <bruteforce> flush global)
pass in inet proto icmp icmp-type { echoreq unreach }
