#!/bin/sh
#
# /etc/rc.d/moused: mouse daemon
#

command='moused'
flags='-F 300 -r high -A 1.5,1.5 -a 0.8 -V -L 3 -t auto'
port="${2:-psm0}"

if [ -c /dev/"$port" ]; then
	pidfile="/var/run/${command}.${port}.pid"
else
	echo >&2 "No device $port found"
	exit 1
fi

case "$1" in
start)		if [ "$RC_BOOT" ] || ! pgrep -q "$command"; then
			if ! limits -C daemon "$command" $flags -I "$pidfile" -p /dev/"$port"; then
				echo >&2 "$command failed"
				exit 1
			fi
		fi
		for ttyv in /dev/ttyv[0-9]; do
			vidcontrol < "$ttyv" -m on
		done
		;;
stop)		if [ -f "$pidfile" ]; then
			kill $(< "$pidfile")
			rm -f "$pidfile"
		fi
		for ttyv in /dev/ttyv[0-9]; do
			vidcontrol < "$ttyv" -m off
		done
		;;
restart)	"$0" stop
		"$0" start
		;;
*)		echo "${0##*/} [start|stop|restart]"
		exit
		;;
esac
