#!/bin/sh
#
# CoreBSD installation script
#

archives=(base.txz kernel.txz)
srcdir='/usr/distsets'
rootpool='zroot'
datapool='zdata'
mountdir='/mnt'

usage() {
	cat <<- INFO
	usage: ${0##*/} -a device [ -a device] [ -b device -b ...] [-r poolname] [-d poolname] [-m mountdir] [-s swapsize] [-u username]
	    -a    rootpool device   (zmirror created if = 2)
	    -b    datapool device   (zstripe created if > 1)
	    -r    rootpool name     (default: zroot)
	    -d    datapool name     (default: zdata)
	    -m    mountdir name     (default: /mnt)
	    -s    swap size in M|G  (default: -)
	    -u    user name         (default: -)
	available devices: $(sysctl -n kern.disks | egrep -o 'a?da[0-9]+' | sort | tr '\n' ' ')
	INFO
	exit
}

while getopts 'a:b:r:d:m:s:u:' option; do
	case "$option" in
		a)	rootpooldevs+=("${OPTARG##/dev/}") ;;
		b)	datapooldevs+=("${OPTARG##/dev/}") ;;
		r)	rootpool="$OPTARG" ;;
		d)	datapool="$OPTARG" ;;
		m)	mountdir="$OPTARG" ;;
		s)	swapsize="$OPTARG" ;;
		u)	username="$OPTARG" ;;
		?)	usage ;;
	esac
done

if (( ${#rootpooldevs[@]} == 0 || ${#rootpooldevs[@]} > 2 )); then
	usage
elif (( ${#rootpooldevs[@]} == 2 )); then
	mode='mirror'
fi
if [ ! -d "$mountdir" ]; then
	echo >&2 "ERROR: $mountdir no such directory"
	exit
fi
if [[ "$swapsize" && "$swapsize" != @([1-9]*([0-9])|+([1-9]*[0-9]).+([0-9])|[0-9].[1-9]*([0-9]))[mgMG] ]]; then
	echo >&2 "ERROR: $swapsize is not a correct size"
	exit
fi
for device in "${rootpooldevs[@]}" "${datapooldevs[@]}"; do
	if [ ! -c /dev/"$device" ]; then
		echo >&2 "ERROR: /dev/${device} is not a block device"
		exit
	fi
done

importedpools=$(zpool list -Ho name)
[ "$importedpools" ] && zpool export -af

i=0; for device in "${rootpooldevs[@]}"; do
	echo "===> Creating GPT scheme on $device"
	gpart destroy -F "$device" &> /dev/null
	gpart create -s gpt "$device" &> /dev/null || exit
	gpart set -a active "$device" &> /dev/null || exit
	gpart add -a 4k -l gptboot"$i" -t freebsd-boot -s 512k "$device" &> /dev/null || exit
	if [[ "$swapsize" && -z "${datapooldevs[@]}" ]]; then
		gpart add -a 1m -l swap"$i" -t freebsd-swap -s "$swapsize" "$device" &> /dev/null || exit
	fi
	gpart add -a 1m -l zroot"$i" -t freebsd-zfs "$device" &> /dev/null || exit
	gpart bootcode -b /boot/pmbr -p /boot/gptzfsboot -i 1 "$device" &> /dev/null || exit
	(( i++ ))
done; unset i

i=0; for device in "${datapooldevs[@]}"; do
	echo "===> Creating GPT scheme on $device"
	gpart destroy -F "$device" &> /dev/null
	gpart create -s gpt "$device" &> /dev/null || exit
	if [ "$swapsize" ]; then
		gpart add -a 1m -l swap"$i" -t freebsd-swap -s "$swapsize" "$device" &> /dev/null || exit
	fi
	gpart add -a 1m -l zdata"$i" -t freebsd-zfs "$device" &> /dev/null || exit
	(( i++ ))
done; unset i

for device in "${rootpooldevs[@]}"; do
	glabel refresh "$device" &> /dev/null || exit
done

echo "===> Creating filesystems on $rootpool"
zpool create \
	-R "$mountdir" \
	-o ashift=12 \
	-O compression=zstd \
	-O checksum=blake3 \
	-O atime=off \
	-O sync=disabled \
	-O acltype=off \
	-O xattr=off \
	-O redundant_metadata=some \
	-m none \
	-f "$rootpool" \
	$mode /dev/gpt/zroot* || exit
zfs allow -g wheel clone,create,destroy,mount,promote,rename,rollback,snapshot "$rootpool" || exit
zfs create -o mountpoint=none "$rootpool"/ROOT || exit
zfs create -o mountpoint=/ -o canmount=noauto "$rootpool"/ROOT/default || exit
zfs mount "$rootpool"/ROOT/default || exit
zpool set bootfs="$rootpool"/ROOT/default "$rootpool" || exit
zfs create -o mountpoint=/usr -o canmount=off "$rootpool"/usr || exit
zfs create -o mountpoint=/usr/src -o setuid=off "$rootpool"/usr/src || exit
zfs create -o mountpoint=/var -o canmount=off "$rootpool"/var || exit
zfs create -o mountpoint=/var/log -o setuid=off -o exec=off "$rootpool"/var/log || exit
zfs create -o mountpoint=/var/tmp -o setuid=off -o exec=on "$rootpool"/var/tmp || exit
if (( ${#datapooldevs[@]} )); then
	echo "===> Creating filesystems on $datapool"
	zpool create \
		-R "$mountdir" \
		-o ashift=12 \
		-O compression=zstd \
		-O checksum=blake3 \
		-O atime=off \
		-O sync=disabled \
		-O acltype=off \
		-O xattr=off \
		-O redundant_metadata=some \
		-m none \
		-f "$datapool" \
		/dev/gpt/zdata* || exit
	zfs allow -g wheel clone,create,destroy,mount,promote,rename,rollback,snapshot "$datapool" || exit
	zfs create -o mountpoint=/usr -o canmount=off "$datapool"/usr || exit
	zfs create -o mountpoint=/usr/obj "$datapool"/usr/obj || exit
	zfs create -o mountpoint=/usr/ports -o setuid=off "$datapool"/usr/ports || exit
	zfs create -o mountpoint=/var -o canmount=off "$datapool"/var || exit
	zfs create -o mountpoint=/var/cache -o setuid=off -o exec=off "$datapool"/var/cache || exit
	zfs create -o mountpoint=/home "$datapool"/home || exit
	mkdir -p "$mountdir"/boot/zfs || exit
	zpool set cachefile="$mountdir"/boot/zfs/zpool.cache "$datapool" || exit
else
	zfs create -o mountpoint=/usr/obj "$rootpool"/usr/obj || exit
	zfs create -o mountpoint=/usr/ports -o setuid=off "$rootpool"/usr/ports || exit
	zfs create -o mountpoint=/var/cache -o setuid=off -o exec=off "$rootpool"/var/cache || exit
	zfs create -o mountpoint=/home "$rootpool"/home || exit
fi

for archive in "${archives[@]}"; do
	echo "===> Verifying checksum of $archive"
	CK=$(sha256 -q "$srcdir"/"$archive")
	awk -v checksum="$CK" -v archive="$archive" -v found=0 '{
		if (archive == $1) {
			found = 1
			if (checksum == $2)
				exit(0)
			else
				exit(1)
		}
	} END {
		if (!found)
			exit(1)
	}' "$srcdir"/MANIFEST
done

for archive in "${archives[@]}"; do
	echo "===> Extracting $archive"
	LC_ALL='C' bsdtar -C "$mountdir" -xf "$srcdir"/"$archive" || exit
done

cat <<- 'END' > "$mountdir"/etc/fstab
	# Device	Mountpoint	FStype	Options					Dump	Pass#
	tmpfs		/tmp		tmpfs	rw,nomtime,mode=1777,size=1g		0	0
END

for i in /dev/gpt/swap*; do
	if [ -e "$i" ]; then
		echo "$i	none		swap	sw					0	0" >> "$mountdir"/etc/fstab
	fi
done

mount -t devfs devfs "$mountdir"/dev
chroot "$mountdir" /usr/bin/passwd root
if [ "$username" ]; then
	chroot "$mountdir" /usr/sbin/pw useradd "$username" -G wheel,operator,video -L russian -m
	chroot "$mountdir" /usr/bin/passwd -l "$username"
fi

dd if=/dev/random of="$mountdir"/boot/entropy bs=4096 count=1 2> /dev/null || exit

echo '===> Edit /boot/loader.conf, /etc/sysctl.conf, /etc/rc.conf, etc. Press Ctrl+D when finished'
chroot "$mountdir" /bin/sh -l 2>&1

echo '===> Unmounting filesystems'
umount "$mountdir"/dev || exit
zfs unmount -a || exit
umount "$mountdir" || exit

echo '--------------------------------------------------------------'
echo ">>> Installation completed at $( date )"
echo '--------------------------------------------------------------'
