#!/bin/sh
#
# /etc/rc.d/ldconfig: configure the shared library cache
#

for dir in /lib /usr/lib /usr/local/lib /usr/local/lib/compat/pkg; do
        [ -d "$dir" ] && libdirs+=("$dir")
done

ldconfig -i "${libdirs[@]}" &
