#!/bin/sh
#
# /etc/rc.d/moused: mouse daemon
#

command='moused'
port="$2"
flags='-F 300 -r high -A 1.5,1.5 -a 0.8 -V -L 3 -t auto -m 1=3 -m 3=1'
pidfile="/var/run/${command}.${port}.pid"

case "$1" in
start)		if [ "$RC_BOOT" ] || ! pgrep -q "$command"; then
			if ! limits -C daemon "$command" $flags -I "$pidfile" -p /dev/"$port"; then
				echo >&2 "$command failed"
				exit 1
			fi
		fi
		vidcontrol -m on
		;;
stop)		if [ -f "$pidfile" ]; then
			rm -f "$pidfile"
		fi
		vidcontrol -m off
		;;
restart)	"$0" stop
		"$0" start
		;;
*)		echo "${0##*/} [start|stop|restart] <port>"
		exit
		;;
esac
