#!/bin/sh
#
# /etc/rc.d/wpa_supplicant: wireless network devices daemon
#

command='wpa_supplicant'
interface="$2"
flags='-s -B -D bsd'
confile="/etc/${command}.conf"
pidfile="/var/run/${command}/${interface}.pid"

if [ -z "$interface" ]; then
	exit
elif [ ! -f "$confile" ]; then
	echo >&2 "$confile not found"
	exit 1
fi

case "$1" in
start)		if ! ifconfig wlan0 &> /dev/null; then
			ifconfig wlan0 create wlandev "$interface"
		fi
		if ! pgrep -q "$command"; then
			if ! limits -C daemon "$command" $flags -c "$confile" -P "$pidfile" -i "$interface"; then
				echo >&2 "$command failed"
				exit 1
			fi
			sleep 0.2
			protect -p $(< "$pidfile")
		fi
		;;
stop)		if [ -f "$pidfile" ]; then
			kill $(< "$pidfile")
			rm -f "$pidfile"
		fi
		if ifconfig wlan0 &> /dev/null; then
			ifconfig wlan0 destroy
		fi
		;;
restart)	"$0" stop
		"$0" start
		;;
*)		echo "${0##*/} [start|stop]"
		exit
		;;
esac
