#!/bin/sh
#
# /etc/rc.d/wpa_supplicant: wireless network devices daemon
#

command=wpa_supplicant
interface="$2"
flags='-s -B -D bsd'
confile=/etc/"$command".conf
pidfile=/var/run/"$command"/"$interface".pid

if [ -z "$interface" ]; then
	echo >&2 "interface not provided"
	exit 1
elif [ ! -f "$confile" ]; then
	echo >&2 "$confile not found"
	exit 1
fi

case "$1" in
start)		if ! pgrep -q "$command"; then
			if ! ifconfig wlan0 &> /dev/null; then
				ifconfig wlan0 create wlandev "$interface" country RU
			fi
			if ! limits -C daemon "$command" $flags -c "$confile" -P "$pidfile" -i wlan0; then
				echo >&2 "$command failed"
				exit 1
			fi
			sleep 0.2
			protect -p $(< "$pidfile")
		fi
		;;
stop)		if [ -f "$pidfile" ]; then
			pkill -F "$pidfile"
			rm -f "$pidfile"
		fi
		if ifconfig wlan0 &> /dev/null; then
			ifconfig wlan0 destroy
		fi
		;;
restart)	"$0" stop
		"$0" start
		;;
*)		echo "${0##*/} [start|stop|restart] <interface>"
		exit
		;;
esac
